version: "3"

services:
  react:
    container_name: react_container
    image: node:10.15
    volumes:
      - ./frontend/react_frontend:/app
    ports:
      - "3000:3000"
    networks:
      - app_network
    restart: on-failure
    depends_on:
      - peerjs
    working_dir: /app
    command: bash -c "npm i && npm start"

  peerjs:
    container_name: peerjs_server
    image: peerjs/peerjs-server
    ports:
      - "9000:9000"
    networks:
      - app_network

  # django:
  #   build: ./backend/django/
  #   container_name: django_container
  #   volumes:
  #     - ./backend/django:/app
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - app_network
  #   command: "python3 manage.py runserver 0.0.0.0:8000"

  # postgres:
  #   image: postgres:latest
  #   container_name: postgres_container
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_HOST_AUTH_METHOD: trust
  #   networks:
  #     - app_network


networks:
  app_network:
